// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CryptoService 是暴露给前端的 Wails 服务，负责状态机、对话框与事件推送。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 取消当前任务。
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(1982436166);
}

/**
 * Clear 重置全部状态（对应原版 "Clear" 按钮）。
 */
export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(284873881);
}

/**
 * ClearDefaultOutputDir 清空默认输出目录。
 */
export function ClearDefaultOutputDir(): $CancellablePromise<void> {
    return $Call.ByID(227688474);
}

/**
 * ClearKeyfiles 清空已选密钥文件。
 */
export function ClearKeyfiles(): $CancellablePromise<void> {
    return $Call.ByID(2134053519);
}

/**
 * ConfirmOverwrite 前端答复覆盖确认。
 */
export function ConfirmOverwrite(overwrite: boolean): $CancellablePromise<void> {
    return $Call.ByID(630134041, overwrite);
}

/**
 * CreateKeyfile 在指定位置生成 32 字节随机密钥文件（与原版一致）。
 */
export function CreateKeyfile(): $CancellablePromise<string> {
    return $Call.ByID(1814919617);
}

/**
 * DropFiles 由前端拖放或选择文件后调用（与原版 onDrop 等价）。
 */
export function DropFiles(paths: string[] | null, asKeyfiles: boolean): $CancellablePromise<void> {
    return $Call.ByID(89894316, paths, asKeyfiles);
}

/**
 * GeneratePassword 生成随机密码。
 */
export function GeneratePassword(length: number, upper: boolean, lower: boolean, nums: boolean, symbols: boolean): $CancellablePromise<string> {
    return $Call.ByID(2620528082, length, upper, lower, nums, symbols);
}

/**
 * GetSavedForm 返回启动时需要恢复的选项与注释。
 */
export function GetSavedForm(): $CancellablePromise<$models.SavedForm> {
    return $Call.ByID(3496841417);
}

/**
 * GetSettings 返回当前设置（设置面板初始化用）。
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2685255021);
}

/**
 * GetState 返回当前完整状态（前端初始化时调用）。
 */
export function GetState(): $CancellablePromise<$models.UIState> {
    return $Call.ByID(2829556437);
}

/**
 * HandleDrop 处理窗口拖放事件（供 main.go 使用）。
 */
export function HandleDrop(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4012196559, paths);
}

/**
 * PasswordStrength 返回密码强度评分（0-4）。
 */
export function PasswordStrength(password: string): $CancellablePromise<number> {
    return $Call.ByID(2734241584, password);
}

/**
 * PickDefaultOutputDir 弹出文件夹选择框设置默认输出目录；取消时返回当前值。
 */
export function PickDefaultOutputDir(): $CancellablePromise<string> {
    return $Call.ByID(1304613982);
}

/**
 * PickFiles 弹出多选文件对话框并作为输入。
 */
export function PickFiles(): $CancellablePromise<void> {
    return $Call.ByID(3989643224);
}

/**
 * PickFolder 弹出文件夹选择对话框并作为输入。
 */
export function PickFolder(): $CancellablePromise<void> {
    return $Call.ByID(3573422453);
}

/**
 * PickKeyfiles 弹出多选对话框添加密钥文件。
 */
export function PickKeyfiles(): $CancellablePromise<void> {
    return $Call.ByID(344733827);
}

/**
 * PickOutput 弹出保存对话框修改输出路径（与原版 "Change" 按钮逻辑一致）。
 */
export function PickOutput(): $CancellablePromise<void> {
    return $Call.ByID(730989548);
}

/**
 * PushState 向前端推送一次当前状态（窗口就绪后调用）。
 */
export function PushState(): $CancellablePromise<void> {
    return $Call.ByID(712981525);
}

/**
 * Save 持久化当前设置（OnShutdown 兜底调用）。
 */
export function Save(): $CancellablePromise<void> {
    return $Call.ByID(2408809473);
}

/**
 * SetComments 同步注释；开启「记住选项」时持久化。
 */
export function SetComments(comments: string): $CancellablePromise<void> {
    return $Call.ByID(1323327214, comments);
}

/**
 * SetKeyfileDropMode 设置拖放是否进入密钥文件列表（密钥文件面板开关）。
 */
export function SetKeyfileDropMode(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1146949471, on);
}

/**
 * SetLanguage 切换界面语言并立即生效（重新推送翻译后的状态）。
 */
export function SetLanguage(lang: string): $CancellablePromise<void> {
    return $Call.ByID(2455888438, lang);
}

/**
 * SetOptions 同步高级选项。解密模式下，弱化文件特征与密钥文件顺序由卷头 flags 决定，
 * 忽略前端对应字段（原版 UI 中解密时这两项为只读）。开启「记住选项」时持久化。
 */
export function SetOptions(o: $models.Options): $CancellablePromise<void> {
    return $Call.ByID(901113394, o);
}

/**
 * SetPassword 同步密码（前端输入时调用）。
 */
export function SetPassword(password: string, cpassword: string): $CancellablePromise<void> {
    return $Call.ByID(2327274013, password, cpassword);
}

/**
 * SetRememberOptions 开关「记住上次的选项状态」；关闭时清空已保存的选项与注释。
 */
export function SetRememberOptions(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(379106127, on);
}

/**
 * Start 开始加解密。返回 "" 表示已启动；返回 "confirm" 表示需要前端确认覆盖；
 * 其余返回值为中文错误/提示文本。
 */
export function Start(): $CancellablePromise<string> {
    return $Call.ByID(3115181800);
}

/**
 * Working 报告当前是否有任务在运行（供关窗拦截）。
 */
export function Working(): $CancellablePromise<boolean> {
    return $Call.ByID(1071323247);
}
