// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Options 是前端同步过来的全部高级选项（对应原版的高级复选框矩阵）。
 */
export interface Options {
    "paranoid": boolean;
    "reedsolo": boolean;
    "deniability": boolean;
    "recursively": boolean;
    "split": boolean;
    "splitSize": string;

    /**
     * 0=KiB 1=MiB 2=GiB 3=TiB 4=Total
     */
    "splitSelected": number;
    "compress": boolean;
    "delete": boolean;
    "autoUnzip": boolean;
    "sameLevel": boolean;
    "keep": boolean;
    "keyfileOrdered": boolean;
}

/**
 * SavedForm 是启动时恢复给前端表单的选项与注释。
 */
export interface SavedForm {
    "has": boolean;
    "options": Options;
    "comments": string;
}

/**
 * Settings 是持久化到本地配置文件的全部设置项。
 */
export interface Settings {
    /**
     * 记住上次的选项状态
     */
    "rememberOptions": boolean;

    /**
     * 默认输出目录（空 = 不设置）
     */
    "defaultOutputDir": string;

    /**
     * "zh" | "en"
     */
    "language": string;

    /**
     * RememberOptions 开启时保存的选项
     */
    "savedOptions": Options;

    /**
     * RememberOptions 开启时保存的注释
     */
    "savedComments": string;
}

/**
 * UIState 是推送给前端的完整界面状态（全部中文）。
 */
export interface UIState {
    /**
     * "" / "encrypt" / "decrypt"
     */
    "mode": string;
    "inputLabel": string;
    "hasInput": boolean;
    "comments": string;
    "commentsDisabled": boolean;
    "keyfileRequired": boolean;
    "keyfileOrderedVolume": boolean;
    "keyfiles": string[] | null;
    "deniabilityVolume": boolean;
    "autoUnzipEligible": boolean;
    "startLabel": string;
    "status": string;
    "statusColor": string;
    "working": boolean;
    "outputFile": string;
    "multipleInputs": boolean;

    /**
     * 变化时前端清空表单
     */
    "resetNonce": number;
}
